name: Newman Run

on:
  push:
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Create directory for artifacts
        run: mkdir testArtifacts

      # Configura o ambiente com Node 20
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Newman and htmlextra reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Tests
        run: newman run ServeRest.postman_collection.json -e serveRest_env.postman_environment.json -r cli,htmlextra --reporter-htmlextra-export testArtifacts/report.html

      - name: Upload Report
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Reports
          path: testArtifacts
