name: Newman Run

on:
  push:
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      # Faz checkout do reposit贸rio
      - name: Check out the code
        uses: actions/checkout@v3

      # Cria o diret贸rio para os artefatos (relat贸rios)
      - name: Create directory for artifacts
        run: mkdir -p testArtifacts

      # Configura o ambiente com Node.js 20
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Instala o Newman e o htmlextra
      - name: Install Newman and htmlextra reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Executa os testes com o Newman
      - name: Run Tests
        run: newman run ServeRest.postman_collection.json -e serveRest_env.postman_environment.json -r cli,htmlextra --reporter-htmlextra-export testArtifacts/report.html || exit 0

      # Faz o upload do relat贸rio gerado
      - name: Upload Report
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Reports
          path: testArtifacts
